name: firebase
description: Dart libraries for Firebase
version: 4.5.0
authors:
- Jana Moudra <jana.moudra@gmail.com>
- Kevin Moore <kevmoo@google.com>
homepage: https://github.com/firebase/firebase-dart

environment:
  sdk: '>=2.0.0-dev.36 <2.0.0'

dependencies:
  http: '^0.12.0'
  js: "^0.6.0"

dev_dependencies:
  googleapis_auth: '^0.2.3+5'
  path: '^1.3.9'
  test: '^0.12.17'
  service_worker: ^0.2.0

  build_runner: ^0.8.0
  build_test: ^0.10.0
  build_web_compilers: ^0.4.0
